### PR TITLE
Example/cv

### PR DESCRIPTION
**Pull request by anthonycorletti**

### CODE REVIEW

**Comment by bogdan-galileo** [comment]
Awesome! The notebooks is super geared towards training with the Beans dataset, and changing to another one would require quite a few changes.

Should we make it more general ? I did the work in https://colab.research.google.com/drive/1kcVplzSJ9UtDDDxvyP4COerZnJr_AXl3?usp=share_link and in that notebook we can select almost any dataset in HF Screenshot 2023-02-03 at 10 13 21 AM

**Review by bogdan-galileo — COMMENTED** [review]
Remove dev URL

**Comment by franz101** [comment]
Haven't had the time yet, but I was thinking we should do a sample dataset repo. where we take only the first x rows. therefore in the ci we could just replace the repo in load_dataset with galileotestdata/[original_dataset] and this would remove CI command

**Comment by bogdan-galileo** [comment]
> 

I think that's a great idea with so many benefits that avoid loading the large dataset and is more predictable. The datasets could even be helpful for other things too. Love that!

I created this ticket https://app.shortcut.com/galileo/story/3607/create-tiny-datasets-to-use-during-ci to keep track of it

**Review by bogdan-galileo — APPROVED** [review]
we did itttttt

**Pull request merged**
